---


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amitaucs/amisoft_property_configuration.git
          search-paths: 'amisoft/*/*'
          #username:
          #password:
  application:
    name: amisoft-config-server
security:
  basic:
    enabled: true
  user:
    name: amisoft
    password: amisoftpass
server:
  port: 9000